title: My Docs Site
description: A place for me to learn how to use the Just the Docs template
theme: just-the-docs

url: https://alpenmo.github.io/my-docs-site

aux_links:
  Checkout the Github Repo: https://github.com/alpenmo/my-docs-site
