title: S&C Associates
description: Demo doc site for the S&C KB
theme: just-the-docs

url: https://alpenmo.github.io/my-docs-site

aux_links:
  "Checkout the Github Repo": https://github.com/alpenmo/my-docs-site

callouts:
    note:
        title: Note
        color: purple
